theme: jekyll-theme-cayman
title: Fluid Font Forge
description: Professional responsive typography for WordPress
show_downloads: true
github:
  repository_url: https://github.com/Mij-Strebor/fluid-font-forge